apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  JAVA_TOOL_OPTIONS: "{{ .Values.global.openTelemetryJavaAgent }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.global.otelExporterEndPoint }}"
  OTEL_METRICS_EXPORTER: "{{ .Values.global.otelMetricsExporter }}"
  OTEL_LOGS_EXPORTER: "{{ .Values.global.otelLogsExporter }}"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.default.svc.cluster.local:9092"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
  TOPIC_PARTITIONS: "1"
  TOPIC_REPLICATION_FACTOR: "1"
  SERVER_PORT: "{{ .Values.backend.service.port }}"