apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
{{/*              protocol: TCP*/}}
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName}}
                  key: SERVER_PORT
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName}}
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: SPRING_DATASOURCE_URL
            - name: TOPIC_PARTITIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: TOPIC_PARTITIONS
            - name: TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: TOPIC_REPLICATION_FACTOR
        {{- if .Values.otel_enabled }}
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: JAVA_TOOL_OPTIONS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: OTEL_METRICS_EXPORTER
            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: OTEL_LOGS_EXPORTER
            - name: OTEL_SERVICE_NAME
              value: {{ .Chart.Name }}
        {{- end }}